name: forgottenlandapp_models
description: Forgotten Land App models
version: 25.09.26+1
publish_to: none

environment:
  sdk: ">=3.3.1"

dependencies:
  intl: ^0.19.0
  universal_html: ^2.2.4
  forgottenlandapp_utils:
    git:
      url: "https://github.com/natanrauber/forgottenlandapp-utils"
      ref: master

dev_dependencies:
  lints: ^4.0.0
