name: forgottenlandapp_models
description: Forgotten Land App models
version: 25.09.30+1
publish_to: none

environment:
  sdk: "3.6.0"

dependencies:
  intl: ^0.20.2
  universal_html: ^2.2.4
  forgottenlandapp_utils:
    git:
      url: "https://github.com/natanrauber/forgottenlandapp-utils"
      ref: master

dev_dependencies:
  lints: ^5.1.1
